PORT: 3000
MONGO_HOST: localhost
MONGO_PORT: 27017
MONGO_DB: job-schedulers
MONGO_USER: 
MONGO_PASS: 
REDIS_HOST: localhost
REDIS_PORT: 6379

# PORT: 3000
# MONGO_HOST: 10.22.13.123
# MONGO_PORT: 27017
# MONGO_DB: mpos360_bgs
# MONGO_USER: mpos360bgs
# MONGO_PASS: 8wzS95YrCMZ5huGq
# REDIS_HOST: localhost
# REDIS_PORT: 6379